services:
  bridge:
    image: ghcr.io/ton-connect/bridge:master
    environment:
      PORT: 8081
      CORS_ENABLE: "true"
      HEARTBEAT_INTERVAL: 10
      RPS_LIMIT: 1000
      CONNECTIONS_LIMIT: 200
    ports:
      - "8081:8081"  # bridge
      - "9103:9103"  # pprof and metrics
    networks:
      - bridge_network
    restart: unless-stopped

networks:
  bridge_network:
    driver: bridge