name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  base:
    name: e2e
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: '${{ env.NVMRC }}'
        cache: 'pnpm'

    - name: Setup dependencies
      run: |
        sudo apt-get install --no-install-recommends -y xvfb
        pnpm install --frozen-lockfile
        pnpm --filter demo-wallet e2e:deps

    - name: Build
      run: |
        pnpm build
        pnpm --filter demo-wallet build:extension
      env:
        VITE_BRIDGE_URL: 'http://localhost:8081/bridge'

    - name: Start TON Connect Bridge
      run: |
        echo "Starting TON Connect Bridge service with docker-compose.memory.yml..."
        docker compose -f docker-compose.bridge.yml up -d
        echo "Waiting for services to be ready..."
        sleep 2

        echo "Checking if TON Connect Bridge service is accessible..."
        max_attempts=30
        attempt=1
        
        while [ $attempt -le $max_attempts ]; do
          echo "Attempt $attempt/$max_attempts: Checking http://localhost:8081/bridge"
          if curl -I -f -s -o /dev/null -w "%{http_code}\n" http://localhost:9103/metrics; then
            echo "‚úÖ TON Connect Bridge service is accessible at http://localhost:8081/bridge"
            break
          else
            echo "‚ùå TON Connect Bridge service not ready yet, waiting 5 seconds..."
            sleep 2
            attempt=$((attempt + 1))
          fi
        done
        
        if [ $attempt -gt $max_attempts ]; then
          echo "‚ùå TON Connect Bridge service failed to start within expected time"
          echo "Docker containers status:"
          docker compose -f docker-compose.bridge.yml ps
          echo "TON Connect Bridge container logs:"
          docker compose -f docker-compose.bridge.yml logs bridge
          exit 1
        fi
        
        echo "üöÄ TON Connect Bridge service is now running and accessible at http://localhost:8081/bridge"
      # uses: ton-connect/bridge/actions/local@master

    - name: Run web e2e specs
      run: xvfb-run pnpm --filter demo-wallet e2e
      env:
        WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
        VITE_BRIDGE_URL: 'http://localhost:8081/bridge'
        ALLURE_BASE_URL: ${{ secrets.ALLURE_BASE_URL }}
        ALLURE_API_TOKEN: ${{ secrets.ALLURE_API_TOKEN }}
        ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}

    - name: Run extension e2e specs
      run: xvfb-run pnpm --filter demo-wallet e2e
      env:
        WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
        E2E_WALLET_SOURCE_EXTENSION: "${{ github.workspace }}/apps/demo-wallet/dist-extension"
        E2E_JS_BRIDGE: true
        ALLURE_BASE_URL: ${{ secrets.ALLURE_BASE_URL }}
        ALLURE_API_TOKEN: ${{ secrets.ALLURE_API_TOKEN }}
        ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}

    - name: Send report
      if: always()
      run: |
        wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
        chmod +x ./allurectl
        ./allurectl upload --endpoint $ALLURE_BASE_URL \
        --token $ALLURE_API_TOKEN \
        --project-id $ALLURE_PROJECT_ID \
        --launch-name "CI for rev:$(git rev-parse --short "$GITHUB_SHA")" \
        apps/demo-wallet/allure-results
      env:
        ALLURE_BASE_URL: ${{ secrets.ALLURE_BASE_URL }}
        ALLURE_API_TOKEN: ${{ secrets.ALLURE_API_TOKEN }}
        ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
