name: e2e extension

on:
  push:
    branches:
      - 'dev/tim/test-fix-actions'
  pull_request:
    branches:
      - main

jobs:
  base:
    name: e2e extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: '${{ env.NVMRC }}'
        cache: 'pnpm'

    - name: Get Playwright version
      id: playwright-version
      run: echo "version=$(pnpm list @playwright/test --json | jq -r '.[0].devDependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Setup dependencies
      run: |
        sudo apt-get install --no-install-recommends -y xvfb
        pnpm install --frozen-lockfile
        pnpm --filter demo-wallet e2e:deps

    - name: Build
      run: |
        pnpm build
      env:
        VITE_BRIDGE_URL: 'http://localhost:8081/bridge'

    - name: Run extension e2e specs
      run: |
        cd apps/demo-wallet
        xvfb-run pnpm playwright test --config e2e.config.ts --retries=3 -g "2258"
      env:
        WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
        E2E_WALLET_SOURCE_EXTENSION: "${{ github.workspace }}/apps/demo-wallet/dist-extension"
        E2E_JS_BRIDGE: true
        ALLURE_BASE_URL: ${{ secrets.ALLURE_BASE_URL }}
        ALLURE_API_TOKEN: ${{ secrets.ALLURE_API_TOKEN_CI }}
        ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
        VITE_DISABLE_NETWORK_SEND: true
    
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-extension
        path: apps/demo-wallet/allure-results/
        retention-days: 1

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-extension
        path: apps/demo-wallet/test-results/
        retention-days: 1