name: Basic build and tests

on:
  push:
  # Allows manual workflow runs with branch selection in UI
  workflow_dispatch: {}


jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, k8s, linux]
    # container:
    #   image: node:22-slim
    #   options: --user root

    steps:

    - name: Check out code
      uses: actions/checkout@v5
    
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

    - uses: pnpm/action-setup@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${{ env.NVMRC }}'
        cache: 'pnpm'

    - name: Set up dependencies
      run: pnpm i --frozen-lockfile

    - name: test
      run: pnpm quality

  e2e-web:
    needs: unit
    uses: ./.github/workflows/e2e_web.yml
    secrets: inherit

  e2e-extension:
    needs: unit
    uses: ./.github/workflows/e2e_extension.yml
    secrets: inherit
